# Generated by Django 6.0.7 on 2026-07-20 20:00

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdocument',
            name='file',
            field=models.FileField(upload_to='members/documents/', validators=[apps.accounts.validators.validate_document_file]),
        ),
    ]
