# Generated by Django 6.0.6 on 2026-07-07 09:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-dumbbell', max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Exercise Categories',
                'db_table': 'exercise_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('abs', 'Abs / Core'), ('glutes', 'Glutes'), ('quads', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], default='chest', max_length=15)),
                ('secondary_muscles', models.CharField(blank=True, max_length=200)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('resistance', 'Resistance Band'), ('cardio_eq', 'Cardio Equipment'), ('none', 'No Equipment')], default='dumbbell', max_length=12)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=14)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('calories_per_min', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.exercisecategory')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general', 'General Fitness')], default='general', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_plans', to='coaches.coach')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='members.member')),
            ],
            options={
                'db_table': 'workout_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_sessions', to='coaches.coach')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_sessions', to='members.member')),
                ('workout_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutplan')),
            ],
            options={
                'db_table': 'pt_sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Workout Session', max_length=200)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('coach_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.workoutplan')),
            ],
            options={
                'db_table': 'workout_sessions',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='10', max_length=20)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_sec', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('actual_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_reps', models.CharField(blank=True, max_length=20)),
                ('actual_weight', models.FloatField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutsession')),
            ],
            options={
                'db_table': 'session_exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general', 'General Fitness')], default='general', max_length=15)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=14)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('days_per_week', models.PositiveIntegerField(default=3)),
                ('session_duration', models.PositiveIntegerField(default=60, help_text='Minutes')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workouts.workouttemplate'),
        ),
    ]
