# Generated by Django 6.0.7 on 2026-07-20 20:00

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcertificate',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='coach_certs/', validators=[apps.accounts.validators.validate_document_file]),
        ),
    ]
