# Generated by Django 6.0.7 on 2026-07-18 23:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('overview', 'Overview'), ('api', 'API Reference'), ('modules', 'Modules'), ('admin', 'Administration')], default='overview', max_length=10)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'system_doc_pages',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('members', 'Members'), ('payments', 'Payments'), ('reports', 'Reports'), ('troubleshooting', 'Troubleshooting')], default='getting_started', max_length=16)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'system_help_articles',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('release_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch')], default='minor', max_length=6)),
                ('summary', models.TextField(blank=True)),
                ('changes', models.JSONField(default=list, help_text='List of change strings')),
                ('released_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'system_release_notes',
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('message', models.TextField(default="We're performing scheduled maintenance. We'll be back shortly!")),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Settings',
                'verbose_name_plural': 'Maintenance Settings',
                'db_table': 'system_maintenance',
            },
        ),
    ]
