# Generated by Django 6.0.6 on 2026-06-29 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color e.g. #3B82F6', max_length=7)),
                ('icon', models.CharField(default='fa-id-card', help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Membership Categories',
                'db_table': 'membership_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount cap for percentage type', max_digits=8, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_single_use', models.BooleanField(default=False)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, help_text='Leave blank for public coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='members.member')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='memberships.discount')),
            ],
            options={
                'db_table': 'membership_coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP'), ('student', 'Student'), ('senior', 'Senior'), ('family', 'Family'), ('corporate', 'Corporate'), ('trial', 'Trial'), ('custom', 'Custom')], default='standard', max_length=15)),
                ('billing_cycle', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('biannual', 'Biannual (6 months)'), ('annual', 'Annual (12 months)'), ('lifetime', 'Lifetime')], default='monthly', max_length=12)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Duration in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_freeze_days', models.PositiveIntegerField(default=30)),
                ('max_members', models.PositiveIntegerField(blank=True, help_text='Max family/corporate members', null=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, help_text='Visible to members')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='memberships.membershipcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'membership_plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='memberships.membershipplan'),
        ),
        migrations.CreateModel(
            name='CorporateMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_address', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('max_employees', models.PositiveIntegerField(default=10)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(limit_choices_to={'plan_type': 'corporate'}, on_delete=django.db.models.deletion.PROTECT, to='memberships.membershipplan')),
            ],
            options={
                'db_table': 'corporate_memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment'), ('trial', 'Trial'), ('grace', 'Grace Period')], default='active', max_length=12)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('refunded', 'Refunded'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('freeze_start', models.DateField(blank=True, null=True)),
                ('freeze_end', models.DateField(blank=True, null=True)),
                ('freeze_days_used', models.PositiveIntegerField(default=0)),
                ('upgrade_type', models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('transfer', 'Transfer')], max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='memberships.coupon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='memberships.discount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member')),
                ('parent_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_members', to='memberships.membersubscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membershipplan')),
                ('previous_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_from', to='memberships.membershipplan')),
            ],
            options={
                'db_table': 'member_subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('max_members', models.PositiveIntegerField(default=4)),
                ('discount_per_member', models.DecimalField(decimal_places=2, default=10, help_text='% discount per additional member', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships_primary', to='members.member')),
                ('plan', models.ForeignKey(limit_choices_to={'plan_type': 'family'}, on_delete=django.db.models.deletion.PROTECT, to='memberships.membershipplan')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_group', to='memberships.membersubscription')),
            ],
            options={
                'db_table': 'family_memberships',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('offer_type', models.CharField(choices=[('seasonal', 'Seasonal Offer'), ('referral', 'Referral Bonus'), ('birthday', 'Birthday Offer'), ('loyalty', 'Loyalty Reward'), ('new_member', 'New Member Offer'), ('bundle', 'Bundle Deal'), ('flash', 'Flash Sale')], max_length=15)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, related_name='offers', to='memberships.membershipplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='memberships.discount')),
            ],
            options={
                'db_table': 'membership_offers',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member_of', to='members.member')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='memberships.familymembership')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_member_sub', to='memberships.membersubscription')),
            ],
            options={
                'db_table': 'family_membership_members',
                'unique_together': {('family', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CorporateEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_member_of', to='members.member')),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='memberships.corporatemembership')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_employee_sub', to='memberships.membersubscription')),
            ],
            options={
                'db_table': 'corporate_employees',
                'unique_together': {('corporate', 'member')},
            },
        ),
    ]
