# Generated by Django 5.2.17 on 2026-08-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='color',
            field=models.CharField(default='#C80036', max_length=7),
        ),
    ]
