# Generated by Django 6.0.7 on 2026-07-18 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField(default='06:00')),
                ('close_time', models.TimeField(default='23:00')),
            ],
            options={
                'db_table': 'business_hours',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year (e.g. national holidays)')),
                ('is_closed', models.BooleanField(default=True, help_text='Gym is closed on this day')),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(default='GymX', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('default_currency', models.CharField(default='EGP', max_length=10)),
                ('currency_symbol', models.CharField(default='EGP', max_length=5)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('dark_mode_default', models.BooleanField(default=False)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('password_require_upper', models.BooleanField(default=True)),
                ('password_require_number', models.BooleanField(default=True)),
                ('password_require_symbol', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('api_key', models.CharField(blank=True, max_length=64)),
                ('webhook_url', models.URLField(blank=True)),
                ('api_rate_limit', models.PositiveIntegerField(default=1000, help_text='Requests per hour')),
                ('smtp_host', models.CharField(blank=True, max_length=150)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=150)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(blank=True, default='Twilio', max_length=50)),
                ('sms_api_key', models.CharField(blank=True, max_length=100)),
                ('sms_sender_id', models.CharField(blank=True, max_length=20)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('payment_provider', models.CharField(blank=True, default='Stripe', max_length=50)),
                ('payment_public_key', models.CharField(blank=True, max_length=150)),
                ('payment_test_mode', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export')], default='update', max_length=8)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size_mb', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('running', 'Running')], default='completed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
