# Generated by Django 5.2.17 on 2026-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#C80036', max_length=7),
        ),
    ]
