# Generated by Django 6.0.6 on 2026-07-02 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_open_time', models.TimeField(default='06:00')),
                ('gym_close_time', models.TimeField(default='23:00')),
                ('max_session_hours', models.PositiveIntegerField(default=4, help_text='Auto-checkout after N hours')),
                ('late_threshold_min', models.PositiveIntegerField(default=30, help_text='Minutes after open = late')),
                ('require_membership', models.BooleanField(default=True, help_text='Block check-in if no active membership')),
                ('allow_multiple_checkin', models.BooleanField(default=False, help_text='Allow re-check-in same day')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'db_table': 'attendance_settings',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in_method', models.CharField(choices=[('qr', 'QR Code'), ('barcode', 'Barcode'), ('manual', 'Manual'), ('face', 'Face Recognition'), ('app', 'Mobile App')], default='manual', max_length=10)),
                ('check_out_method', models.CharField(blank=True, choices=[('qr', 'QR Code'), ('barcode', 'Barcode'), ('manual', 'Manual'), ('face', 'Face Recognition'), ('app', 'Mobile App')], max_length=10)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('left', 'Left Early'), ('absent', 'Absent')], default='present', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['date', 'member'], name='attendance__date_c4adce_idx'), models.Index(fields=['check_in'], name='attendance__check_i_9471e8_idx')],
            },
        ),
    ]
